name: CI Pipeline

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t authbase_backend .
    - name: Tagging image
      run: docker tag authbase_backend:latest hencyd/authbase_backend:latest
    - name: Push to Dockerhub
      run: docker push hencyd/authbase_backend:latest
