name: CI/CD Pipeline

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Remove existing repository
      run: rm -rf Authbase-Backend || true
    - name: Clone the repository
      run: git clone -b dev git@github.com:hencydsouza/Authbase-Backend.git
    - name: Copy the .env file
      run: cp /home/ubuntu/actions-runner/.env Authbase-Backend
    - name: Stop and remove existing container
      run: |
        sudo docker stop authbase_backend_container || true
        sudo docker rm -f authbase_backend_container || true
    - name: Prune old Docker images
      run: |
        sudo docker image prune -f
    - name: Build the Docker image
      run: sudo docker build -t authbase_backend Authbase-Backend
    - name: Run the Docker container
      run: sudo docker run -d --name authbase_backend_container -p 8000:8000 authbase_backend