name: CD Pipeline

on:
  push:
    branches: [ "dev" ]

jobs:

  build and deploy:

    runs-on: self-hosted

    steps:
    - name: Clone the repository
      run: git clone git@github.com:hencydsouza/Authbase-Backend.git
    - name: Change directory
      run: cd Authbase-Backend
    - name: Switch to dev branch
      run: git checkout dev
    - name: Copy the .env file
      run: cp /home/ubuntu/actions-runner/.env .
    - name: Stop and remove existing container
      run: |
        sudo docker stop authbase_backend_container || true
        sudo docker rm -f authbase_backend_container || true
    - name: Prune old Docker images
      run: |
        sudo docker image prune -f
    - name: Build the Docker image
      run: sudo docker build -t authbase_backend .
    - name: Run the Docker container
      run: sudo docker run -d --name authbase_backend_container -p 8000:8000 --env-file .env authbase_backend